### ISSUE TITLE
Unable to parse when using time offset

### ISSUE THREAD

**Issue by mostolog** [paulwellnerbou/java-time-parse-debugger#1]
Can't parse "11/Oct/2017:13:30:26 +0200" using format "dd/MMM/yyyy:HH:mm:ss Z"

**Comment by paulwellnerbou** [comment]
Fixed. Escaping + on ajax request.

**Comment by paulwellnerbou** [comment]
Thanks for the bug ticket. Fixed now and just deployed to heroku.
